exclude:
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md
- dap.md
- uxtesting.md
- work
- ".sass-cache"

# defaults
defaults:
  -
    scope:
      path: ""
      type: agencies
    values:
      layout: default

collections:
  agencies:
    output: true
    permalink: /:path/

# Site title and description 
title: "analytics.usajobs.gov | A Window into USAJOBS's Web Traffic."
description: "Providing data and insights into web traffic to USAJOBS.gov Published by the USAJOBS Data & Analytics Team."

# Site's own URL
url: https://analytics.usa.gov 

# Default dropdown title, will not appear if there are no sub-pages
dropdown_title: All Participating Websites

# Default data url
data_url: https://analytics.usa.gov/data/live

# Baseurl
baseurl: /analytics.usajobs.gov

# GitHub information
org_name: GSA
repo_name: analytics.usa.gov

# twitter information
twitter: usgsa

sass:
  sass_dir: sass
  style: nested
